# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

**STEP 1**

In [196]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

**STEP 2**

In [197]:
#Loading in the Kaggle aviation dataset
df = pd.read_csv("data/AviationData.csv", encoding= "ISO-8859-1")

#Show the first 5 rows of the dataset
print(df.head())

         Event.Id Investigation.Type Accident.Number  Event.Date  \
0  20001218X45444           Accident      SEA87LA080  1948-10-24
1  20001218X45447           Accident      LAX94LA336  1962-07-19
2  20061025X01555           Accident      NYC07LA005  1974-08-30
3  20001218X45448           Accident      LAX96LA321  1977-06-19
4  20041105X01764           Accident      CHI79FA064  1979-08-02

          Location        Country   Latitude  Longitude Airport.Code  \
0  MOOSE CREEK, ID  United States        NaN        NaN          NaN
1   BRIDGEPORT, CA  United States        NaN        NaN          NaN
2    Saltville, VA  United States  36.922223 -81.878056          NaN
3       EUREKA, CA  United States        NaN        NaN          NaN
4       Canton, OH  United States        NaN        NaN          NaN

  Airport.Name  ... Purpose.of.flight Air.carrier Total.Fatal.Injuries  \
0          NaN  ...          Personal         NaN                  2.0
1          NaN  ...          Personal         NaN                  4.0
2          NaN  ...          Personal         NaN                  3.0
3          NaN  ...          Personal         NaN                  2.0
4          NaN  ...          Personal         NaN                  1.0

  Total.Serious.Injuries Total.Minor.Injuries Total.Uninjured  \
0                    0.0                  0.0             0.0
1                    0.0                  0.0             0.0
2                    NaN                  NaN             NaN
3                    0.0                  0.0             0.0
4                    2.0                  NaN             0.0

  Weather.Condition  Broad.phase.of.flight   Report.Status Publication.Date
0               UNK                 Cruise  Probable Cause              NaN
1               UNK                Unknown  Probable Cause       19-09-1996
2               IMC                 Cruise  Probable Cause       26-02-2007
3               IMC                 Cruise  Probable Cause       12-09-2000
4               VMC               Approach  Probable Cause       16-04-1980

[5 rows x 31 columns]

C:\Users\kevin\AppData\Local\Temp\ipykernel_26856\804208491.py:2: DtypeWarning: Columns (6,7,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/AviationData.csv", encoding= "ISO-8859-1")

In [198]:
# Initially, I will view the shape of the dataset to see how many rows and columns it has. This will give me an idea of the size of the dataset and how much data I am working with.
print("\nDataset Shape:")
print(df.shape)
# Next, I will get general information about the dataset, such as the number of non-null values in each column and the data types of each column. 
# This will help me identify any missing values or potential issues with the data types.
print("\nDataset Info:")
print(df.info())

#Statistical summary of the dataset, which will give me an idea of the distribution of the data and any potential outliers.
print("\nStatistical Summary:")
display(df.describe())

#Check for missing values in the dataset. This will help me identify any columns that may need to be cleaned or imputed.
print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape:
(88889, 31)

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB
None

Statistical Summary:

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

Missing Values:
Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

**STEP 3**

In [199]:
#What i'll do next is to inspect the the relevant columns that the client is interested in an analysis of

#1. Aircraft categories, how many of them are there and any total number of missing values
print("Aircraft categories;") # print aircraft categories in the data
print(df["Aircraft.Category"].value_counts(dropna=False))

#2. Amateur builds. Client is only interested in professionally built pieces
print("\nAmateur built;")
print(df["Amateur.Built"].value_counts(dropna=False))

#3. Event date. From the df.info() this column is stored as an object and should be a datetime datatype
print("\nEvent date;")
print(df["Event.Date"].head())

Aircraft categories;
Aircraft.Category
NaN                  56602
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64

Amateur built;
Amateur.Built
No     80312
Yes     8475
NaN      102
Name: count, dtype: int64

Event date;
0    1948-10-24
1    1962-07-19
2    1974-08-30
3    1977-06-19
4    1979-08-02
Name: Event.Date, dtype: object

**STEP 3.1. Data cleaning, filtering aircrafts and events**

In [200]:
#After inspection weve noticed some few problems such as missing values and incorrect formats that we need to first fix
# In the aircraft category 56602 values are missing, we can drop these because client is specific on wanting airplanes only, rows without categories cant be classified
df = df.dropna(subset=["Aircraft.Category"])

# We will also drop the 102 NaN values for Amateur builds since we cant determine whether they were professional or amateur builds
df = df.dropna(subset=["Amateur.Built"])

# Finally, I will convert event date to a datetime format
df["Event.Date"] = pd.to_datetime(df["Event.Date"])

In [201]:
# Now we filter the data based on clients needs
#1. Get the airplanes category only
df = df[df["Aircraft.Category"] == "Airplane"]

#2. Get the professional builds only. From the amateur builds method the professional ones are marked by boolean 'No'
df = df[df["Amateur.Built"] == "No"]

#3. Get only the events from the past 40 years
# So here we can get today's timestamp using the pd.timestamp special class and subtract it to the number of years we need (40) using DateOffset class
valid_date = pd.Timestamp.today() - pd.DateOffset(years=40)
df = df[df["Event.Date"] >= valid_date]

# Get the new shape
print("New filtered dataset shape", df.shape)

New filtered dataset shape (21416, 31)

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

**STEP 4**

In [202]:
# First thing is to construct metrics for fatal/serious injuries using derived fields
# So inorder to estimate the total number of passengers we need to use the injuries figures and since it has the injuries numbers we can use that

passenger_injury_columns = [
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured"
]

df[passenger_injury_columns] = df[passenger_injury_columns].fillna(0) # fill in the missing values with 0 to make calculations smoother

# Now estimate the total number of passengers
df["Total.Passengers"] = (
    df["Total.Fatal.Injuries"] + df["Total.Serious.Injuries"] + df["Total.Minor.Injuries"] +df["Total.Uninjured"]
)

In [203]:
# Total serious/fatal injuries
df["Fatal.Serious.Injuries"] = (
    df["Total.Fatal.Injuries"]
    + df["Total.Serious.Injuries"]
)


# Avoided dividing by zero
df["Total.Passengers"] = df["Total.Passengers"].replace(0, np.nan)

# Now get the probability of a passenger suffering a fatal or serious injury
df["Fatal.Serious.Rate"] = (
    df["Fatal.Serious.Injuries"]
    / df["Total.Passengers"]
)

print(df["Fatal.Serious.Rate"].describe())

print(
    "Records with a rate above zero:",
    (df["Fatal.Serious.Rate"] > 0).sum()
)

print(
    "Maximum injury rate:",
    df["Fatal.Serious.Rate"].max()
)

df.loc[
    df["Fatal.Serious.Rate"] > 0,
    [
        "Make",
        "Model",
        "Total.Passengers",
        "Total.Fatal.Injuries",
        "Total.Serious.Injuries",
        "Fatal.Serious.Rate"
    ]
].head(10)

#The reason for this is if we dont have the total number of passengers we cant really gage how fatal the accident was,
# for instance if we had an accident wuth 5 passengers and all 5 were seriously injured it was dangerous than having another with
# 50 and only 10 were injured, this is how we get a rating of seriousness of the accident

count    20512.000000
mean         0.283869
std          0.431699
min          0.000000
25%          0.000000
50%          0.000000
75%          0.800000
max          1.000000
Name: Fatal.Serious.Rate, dtype: float64
Records with a rate above zero: 6753
Maximum injury rate: 1.0

,Make,Model,Total.Passengers,Total.Fatal.Injuries,Total.Serious.Injuries,Fatal.Serious.Rate
16646,Mooney,M-20C,10.0,10.0,0.0,1.000000
16647,Swearingen,SA-226TC,10.0,10.0,0.0,1.000000
16837,Boeing,707-323B,135.0,1.0,0.0,0.007407
19931,Piper,PA-38,1.0,1.0,0.0,1.000000
20084,Boeing,757-225,193.0,0.0,1.0,0.005181
20693,Helio,HST-550A,1.0,1.0,0.0,1.000000
21901,Airbus Industrie,A-300B4-203,227.0,0.0,1.0,0.004405
22096,Boeing,747SP-21,222.0,0.0,1.0,0.004505
22110,Cessna,310R,2.0,2.0,0.0,1.000000
22125,Univair,GLOBE GC-1B,1.0,0.0,1.0,1.000000

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [204]:
# I first inspected
print(df["Aircraft.damage"].value_counts(dropna=False))

#Then clean by filling the unknown values
df["Aircraft.damage"] = df["Aircraft.damage"].fillna("Unknown")

# A column to track whether an aircraft was destroyed or not
df["Aircraft.Destroyed"] = (df["Aircraft.damage"] == "Destroyed").astype(int)

Aircraft.damage
Substantial    16981
Destroyed       2303
NaN             1223
Minor            812
Unknown           97
Name: count, dtype: int64

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

**STEP 5**

In [205]:
# We first need to inspect the data to see what problems it has
print(df["Make"].value_counts(dropna=False).head(50))

Make
CESSNA                            4867
PIPER                             2803
Cessna                            2269
Piper                             1182
BOEING                            1037
BEECH                             1018
Beech                              411
MOONEY                             238
Boeing                             225
CIRRUS DESIGN CORP                 218
AIR TRACTOR INC                    217
AIRBUS                             215
BELLANCA                           158
AERONCA                            149
MAULE                              144
Mooney                             125
EMBRAER                            123
Air Tractor                        117
LUSCOMBE                            95
STINSON                             91
DEHAVILLAND                         91
CHAMPION                            91
AIR TRACTOR                         89
CIRRUS                              80
NORTH AMERICAN                      79
GRUMMAN                             77
DIAMOND AIRCRAFT IND INC            74
AVIAT AIRCRAFT INC                  72
Maule                               71
AERO COMMANDER                      68
Grumman                             67
Champion                            67
BOMBARDIER INC                      65
MCDONNELL DOUGLAS                   64
SOCATA                              63
Bellanca                            61
TAYLORCRAFT                         61
GRUMMAN ACFT ENG COR-SCHWEIZER      58
Cirrus                              57
RAYTHEON AIRCRAFT COMPANY           53
ROCKWELL INTERNATIONAL              52
Aeronca                             51
GRUMMAN AMERICAN AVN. CORP.         48
Luscombe                            46
AMERICAN CHAMPION AIRCRAFT          46
Aviat                               42
Mcdonnell Douglas                   42
BOMBARDIER                          42
FLIGHT DESIGN GMBH                  42
De Havilland                        38
Name: count, dtype: int64

**Cleaning tasks identified from inspecting the data were;**

1. Removing any leading and trailing spaces from manufacturer names
2. Removing rows with missing manufacturer names
3. Standardize the text by changing all manufacturer names to uppercase
4. Keep only manufacturers with at least 50 accident records for a better analysis

In [206]:
#Execute cleaning
#1.
df["Make"] = df["Make"].str.strip()
#2.
df = df.dropna(subset=["Make"])
#3.
df["Make"] = df["Make"].str.upper()
#4.
# Count the accidents by manufacturer
manufacturer_accidents = df["Make"].value_counts()
# Manufacturer  with at least 50 records
valid_manufacturer_accidents = manufacturer_accidents[manufacturer_accidents >= 50].index

#Check that the cleaning was proper
print("Chosen manufacturers:", df["Make"].nunique())
print(df["Make"].value_counts().head(50))

Chosen manufacturers: 1087
Make
CESSNA                            7136
PIPER                             3985
BEECH                             1429
BOEING                            1262
MOONEY                             363
AIRBUS                             243
CIRRUS DESIGN CORP                 220
AIR TRACTOR INC                    219
BELLANCA                           219
MAULE                              215
AIR TRACTOR                        206
AERONCA                            200
CHAMPION                           158
EMBRAER                            153
GRUMMAN                            144
LUSCOMBE                           141
CIRRUS                             137
STINSON                            129
MCDONNELL DOUGLAS                  108
NORTH AMERICAN                     106
DEHAVILLAND                         95
TAYLORCRAFT                         93
AERO COMMANDER                      90
AVIAT AIRCRAFT INC                  76
SOCATA                              75
DIAMOND AIRCRAFT IND INC            74
DE HAVILLAND                        72
AVIAT                               70
BOMBARDIER INC                      65
RAYTHEON AIRCRAFT COMPANY           62
ROCKWELL INTERNATIONAL              58
GRUMMAN ACFT ENG COR-SCHWEIZER      58
AYRES                               55
AMERICAN CHAMPION AIRCRAFT          52
ERCOUPE                             52
BOMBARDIER                          50
DIAMOND                             49
GRUMMAN AMERICAN AVN. CORP.         49
FLIGHT DESIGN GMBH                  49
LEARJET                             47
ROCKWELL                            42
AIRBUS INDUSTRIE                    42
WACO                                41
AYRES CORPORATION                   41
DOUGLAS                             39
MOONEY AIRCRAFT CORP.               34
COSTRUZIONI AERONAUTICHE TECNA      33
FAIRCHILD                           33
SWEARINGEN                          32
EVEKTOR-AEROTECHNIK AS              30
Name: count, dtype: int64

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

**STEP 6**

In [207]:
#Identify and delete the NaN - this is bcoz the model is a must for identifying aircraft types. If it's missing, we cannot uniquely identify the aircraft.
df = df.dropna(subset=["Model"])

# Now lets inspect and see the most common aircraft models
print(df["Model"].value_counts().head(20))

# Get the total of unique models
print("\nUnique Models:", df["Model"].nunique())

# Inspect and count each model by its manufacturer
manufacturer_model_counts = (
    df.groupby(["Make", "Model"])
      .size()
      .sort_values(ascending=False)
)

print(manufacturer_model_counts.head(10))

# Standardize Make and Model,removing extra spaces and standardizing capitalization before combining them.
df["Make"] = df["Make"].str.strip().str.upper()
df["Model"] = df["Model"].str.strip().str.upper()

# Create a unique aircraft type identifier since model names are not guaranteed to be unique across manufacturers, combine Make and Model.
df["Aircraft.Type"] = df["Make"] + " " + df["Model"]

# Verifying the new column
print("\nAircraft Type examples:")
print(df[["Make", "Model", "Aircraft.Type"]].head())

print("\nNumber of unique aircraft types:")
print(df["Aircraft.Type"].nunique())

Model
172          772
737          403
152          315
182          304
172S         278
PA28         273
SR22         265
172N         250
180          213
A36          189
172M         180
PA-18-150    180
150          179
PA-28-140    168
172P         143
140          117
172R         110
170B         107
PA-28-161    106
PA-28-180    105
Name: count, dtype: int64

Unique Models: 3547
Make    Model
CESSNA  172      769
BOEING  737      403
CESSNA  152      314
        182      304
        172S     276
PIPER   PA28     273
CESSNA  172N     249
        180      213
        172M     180
        150      179
dtype: int64

Aircraft Type examples:
             Make     Model        Aircraft.Type
16646      MOONEY     M-20C         MOONEY M-20C
16647  SWEARINGEN  SA-226TC  SWEARINGEN SA-226TC
16837      BOEING  707-323B      BOEING 707-323B
17151       PIPER     PA 16          PIPER PA 16
19663  GULFSTREAM     AA-5B     GULFSTREAM AA-5B

Number of unique aircraft types:
4348

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

**STEP 7**

In [208]:
# First i inspected the columns
# Engine Type
print("Engine Type")
print(df["Engine.Type"].value_counts(dropna=False))

# Weather Condition
print("\nWeather Condition")
print(df["Weather.Condition"].value_counts(dropna=False))

# Number of Engines
print("\nNumber of Engines")
print(df["Number.of.Engines"].describe())

# Purpose of Flight
print("\nPurpose of Flight")
print(df["Purpose.of.flight"].value_counts(dropna=False))

# Broad Phase of Flight
print("\nBroad Phase of Flight")
print(df["Broad.phase.of.flight"].value_counts(dropna=False))

Engine Type
Engine.Type
Reciprocating      14996
NaN                 3943
Turbo Prop          1245
Turbo Fan            920
Turbo Jet            132
Unknown              132
Geared Turbofan       12
Turbo Shaft           11
Electric               5
UNK                    1
Name: count, dtype: int64

Weather Condition
Weather.Condition
VMC    17053
NaN     2970
IMC     1066
Unk      215
UNK       93
Name: count, dtype: int64

Number of Engines
count    18851.000000
mean         1.177391
std          0.428111
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          8.000000
Name: Number.of.Engines, dtype: float64

Purpose of Flight
Purpose.of.flight
Personal                     11705
NaN                           3670
Instructional                 2751
Aerial Application             930
Business                       497
Unknown                        365
Positioning                    348
Aerial Observation             161
Skydiving                      158
Other Work Use                 155
Flight Test                    120
Ferry                          103
Executive/corporate            103
Banner Tow                      89
Public Aircraft - Federal       52
Air Race show                   48
Public Aircraft                 38
Glider Tow                      35
Public Aircraft - State         24
Firefighting                    17
Public Aircraft - Local         12
ASHO                             5
Air Race/show                    4
Air Drop                         3
PUBS                             3
External Load                    1
Name: count, dtype: int64

Broad Phase of Flight
Broad.phase.of.flight
NaN            18606
Landing         1252
Takeoff          503
Cruise           261
Approach         231
Maneuvering      163
Taxi             109
Go-around         89
Descent           69
Climb             56
Standing          44
Unknown           12
Other              2
Name: count, dtype: int64

**Cleaning Other Columns Task**

1. Engine.Type
- Remove leading and trailing spaces
- Replace placeholder values such as "UNKNOWN" with missing values(np.nan)
- Standardize capitalization

2. Weather.Condition
- Standardize text formatting
- Remove leading and trailing spaces
- Replace placeholder values such as "UNK" with missing values

3. Number.of.Engines
- Remove impossible values
- Keep valid engine counts

4. Purpose.of.flight
- Group categories with very few observations into "Others" for ease in analysis

5. Broad.phase.of.flight
- Standardize capitalization
- Group rare phases into "Other"

In [209]:
# Execution of cleaning tasks
# 1.Engine Type
df["Engine.Type"] = df["Engine.Type"].str.strip()
df["Engine.Type"] = df["Engine.Type"].replace("UNKNOWN", np.nan)
df["Engine.Type"] = df["Engine.Type"].str.upper()

# 2.Weather Condition
df["Weather.Condition"] = df["Weather.Condition"].str.upper()
df["Weather.Condition"] = df["Weather.Condition"].str.strip()
df["Weather.Condition"] = df["Weather.Condition"].replace("UNK", np.nan)

# 3.Number of Engines
df = df[df["Number.of.Engines"] > 0]

# 4.Purpose of Flight
purpose_counts = df["Purpose.of.flight"].value_counts()
rare_purpose = purpose_counts[purpose_counts < 50].index

df["Purpose.of.flight"] = df["Purpose.of.flight"].replace(
    rare_purpose,
    "Other"
)

#5. Broad Phase of Flight

phase_counts = df["Broad.phase.of.flight"].value_counts()
rare_phase = phase_counts[phase_counts < 50].index

df["Broad.phase.of.flight"] = df["Broad.phase.of.flight"].replace(
    rare_phase,
    "Other"
)

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [210]:
#First inspect and count non-null values in each column
non_null_values_count = df.count()
# Display them
print(non_null_values_count.sort_values())

#Filter and keep columns with more than 20000 non-null values. If we run this no columns have non null values over 19000 so all our columns will be deleted. So i skipped this step for retaining meaningful dataset
#keep_cols = non_null_values_count[non_null_values_count > 20000].index
#df = df[keep_cols]

print("Remaining columns:", len(df.columns))
print(df.columns.tolist())

Schedule                   1869
Broad.phase.of.flight      2780
Air.carrier                9182
Airport.Code              13342
Airport.Name              13424
Report.Status             16059
Engine.Type               16898
Purpose.of.flight         16915
Weather.Condition         17436
Longitude                 18043
Latitude                  18049
Publication.Date          18468
Total.Passengers          18536
Fatal.Serious.Rate        18536
Injury.Severity           18577
FAR.Description           18709
Registration.Number       18818
Country                   18841
Location                  18841
Event.Id                  18842
Total.Uninjured           18842
Fatal.Serious.Injuries    18842
Total.Minor.Injuries      18842
Total.Serious.Injuries    18842
Number.of.Engines         18842
Aircraft.Destroyed        18842
Amateur.Built             18842
Model                     18842
Make                      18842
Aircraft.Category         18842
Aircraft.damage           18842
Event.Date                18842
Accident.Number           18842
Investigation.Type        18842
Total.Fatal.Injuries      18842
Aircraft.Type             18842
dtype: int64
Remaining columns: 36
['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description', 'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date', 'Total.Passengers', 'Fatal.Serious.Injuries', 'Fatal.Serious.Rate', 'Aircraft.Destroyed', 'Aircraft.Type']

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [211]:
#Save as a CSV file
df.to_csv("data/AviationData_Clean.csv", index=False)
print("Dataset saved successfully")

Dataset saved successfully